# <font color="green">__NumPy Quick Tutorial__ </font>
***
NumPy can be used to create n-dimentonal arrays and process them. <br><br>
You must install numpy before you can run this code: `pip install numpy`


* The following code will create a 2D array. In NumPy, the array is called <b><font color="pink">"ndarray"</font></b> or array for short. But whenever there is a mention to ndarray, it is the NumPy array.

In [1]:
import numpy as np

a = np.array([[1,2,3],[9,8,7]])
print("The array:")
print(a)
print("array has {} dimetions".format(a.ndim))   # number of dimetions 2
print("array has shape {}".format(a.shape))  # the shape
print("array has size {}".format(a.size))  # total number of elements

The array:
[[1 2 3]
 [9 8 7]]
array has 2 dimetions
array has shape (2, 3)
array has size 6


* arange can create an array with a start value, stop value and a step
* arrange can be used for integers or fractional numbers

In [2]:
b = np.arange(3, 15, 2) # start by 3, stop 15, step is 2
print("An integer array is {}".format(b))
print("The array after reshaping to 2 rows and 3 columns using reshape")
print(b.reshape(2, 3))

f = np.arange(3, 15, 0.5) # start by 3, stop 15, step is 0.5
print("A fractional array is {}".format(f))
print("The array after reshaping to 4 rows and 6 columns using reshape")
print(f.reshape(4, 6))

An integer array is [ 3  5  7  9 11 13]
The array after reshaping to 2 rows and 3 columns using reshape
[[ 3  5  7]
 [ 9 11 13]]
A fractional array is [ 3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5
 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5]
The array after reshaping to 4 rows and 6 columns using reshape
[[ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]
 [12.  12.5 13.  13.5 14.  14.5]]


* We can create arrays with zeros and ones

In [3]:
ones = np.ones((2,3))
print("Ones(2,3)\n", ones)
zeros = np.zeros((2,3))
print("Zeros(2,3)\n",zeros)

Ones(2,3)
 [[1. 1. 1.]
 [1. 1. 1.]]
Zeros(2,3)
 [[0. 0. 0.]
 [0. 0. 0.]]


### Basic Operations
***
You can directly apply the operation you want on the array.

In [ ]:
print("Array after adding 3 to each element: {}".format(b+3))
print("Array after dividing each element by 2: {}".format(b/2))
print("Array afterfg squer each element: {}".format(b**2))
print("Array after squer each element then subtract it: {}".format(b**2 - b))
print("Array after taking cosine each element * pi: {}".format(np.cos(b * np.pi)))


### Array Operations
The default is the elementwise operations. The * operator works on each element. To do Matrix multiplication, use the @ operator

In [ ]:
a1 = np.array([1,2])
b1 = np.array([[4,5], [2, 3]])
print("Element-wise multiplication:\n", a1*b1)
print("Matrix multiplication:\n", a1@b1)


Create a random array and get its max, min, average, sum, and sorted values

In [ ]:
rg = np.random.default_rng(1)     # create instance of default random number generator
ra = rg.random((2,3))
print("Random array:\n{}".format(ra))
print("Random array sum: {}".format(ra.sum()))
print("Random array min: {}".format(ra.min()))
print("Random array max: {}".format(ra.max()))
print("Random array average: {}".format(np.average(ra)))
print("Random array sorted: {}".format(np.sort(ra)))

## Learn more
Check NumPy documentations at [https://numpy.org/doc/stable/user/index.html](https://numpy.org/doc/stable/user/index.html)
<br>
W3Schools Tutorial: [https://www.w3schools.com/python/numpy/](https://www.w3schools.com/python/numpy/)